modLoader="javafml"
loaderVersion="[44,)"
license="All Rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted/issues"

[[mods]]
modId="uncrafted"
version="4.1.2"
displayName="Uncrafted"
itemIcon="minecraft:crafting_table"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Uncrafted.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted"
logoFile="logo.png"
authors="XxRexRaptorxX (RexRaptor)"
description='''
A simple Mod which adds Crafting and Smelting recipes, to make blocks and items, that are uncraftable.
'''


[[dependencies.uncrafted]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.uncrafted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
