modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:crafting_table"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Uncrafted.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''A simple mod which adds crafting and smelting recipes, to make blocks and items, that are uncraftable.'''


[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

