modLoader="javafml"
loaderVersion="[38,)"
license="All Fights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted"

[[mods]]
modId="uncrafted"
version="4.0.0pre1"
displayName="Uncrafted"
itemIcon="minecraft:crafting_table"
logoFile="logo.png"
authors="XxRexRaptorxX (RexRaptor)"
description='''
A simple Mod which adds Crafting and Smelting recipes, to make blocks and items, that are uncraftable.
'''


[[dependencies.uncrafted]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.uncrafted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
