modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:crafting_table"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Uncrafted/refs/heads/main/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/uncrafted"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''A simple mod that adds dozens of new crafting and smelting recipes!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/crafting_table_front.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="magmacore"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
reason="Provides basic code and features such as update-checker"
type="required"
versionRange="${magmacore_version_range}"
ordering="AFTER"
side="BOTH"

