name: Sync versions.json on PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

jobs:
  sync-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Sync versions.json from main
        run: |
          if git rev-parse --verify origin/main >/dev/null 2>&1; then
            MAIN_BRANCH="main"
          elif git rev-parse --verify origin/master >/dev/null 2>&1; then
            MAIN_BRANCH="master"
          else
            echo "Error: Neither main nor master branch found"
            exit 1
          fi
          
          echo "Using branch: origin/$MAIN_BRANCH"
          
          # check if versions.json in main branch exists
          if git cat-file -e "origin/$MAIN_BRANCH:versions.json" 2>/dev/null; then
            # get versions.json main branch
            git show "origin/$MAIN_BRANCH:versions.json" > versions.json
            echo "Synced versions.json from $MAIN_BRANCH"
          
            # test
            if ! git diff --quiet versions.json; then
              echo "versions.json has been updated"
              git add versions.json
              git commit -m "Auto-sync: Update versions.json from $MAIN_BRANCH branch"
              git push origin ${{ github.head_ref }}
            else
              echo "versions.json is already up to date"
            fi
          else
            echo "Warning: versions.json not found in $MAIN_BRANCH branch"
          fi